"""initial migration

Revision ID: 5f5af436c3ef
Revises: e04cdd5bd995
Create Date: 2019-05-04 13:26:11.080427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5af436c3ef'
down_revision = 'e04cdd5bd995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
